- name: Install NGINX
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
      ansible_python_interpreter: /usr/bin/python3
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: Install NGINX
    apt:
      name: nginx
      state: present
